<?xml version="1.0"?>

<robot name="njust_v2_fixed" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="DEBUG" default="false"/>

    <xacro:include filename="$(find njust_v2_fixed_description)/xacro/const.xacro"/>
    <xacro:include filename="$(find njust_v2_fixed_description)/xacro/materials.xacro"/>
    <xacro:include filename="$(find njust_v2_fixed_description)/xacro/leg.xacro"/>
    <xacro:include filename="$(find njust_v2_fixed_description)/xacro/stairs.xacro"/>
    <xacro:include filename="$(find njust_v2_fixed_description)/xacro/gazebo.xacro"/>
    <xacro:include filename="$(find njust_v2_fixed_description)/xacro/transmission.xacro"/>
    <!-- <xacro:include filename="$(find a1_gazebo)/launch/stairs.urdf.xacro"/> -->

    <!-- <xacro:stairs stairs="15" xpos="0" ypos="0" zpos="0" /> -->

    <!-- Rollover Protection mode will add an additional stick on the top, use "true" or "false" to switch it. -->
    <xacro:property name="rolloverProtection" value="false"/>

    <!-- Debug mode will hung up the robot, use "true" or "false" to switch it. -->
    <xacro:if value="$(arg DEBUG)">
        <link name="world"/>
        <joint name="base_static_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="world"/>
            <child link="base"/>
        </joint>
    </xacro:if> 

    <link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="floating_base" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base"/>
        <child link="trunk"/>
    </joint>

    <link name="trunk">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://njust_v2_fixed_description/meshes/base_link.STL" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://njust_v2_fixed_description/meshes/base_link.STL" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <!-- <collision>
            <geometry>
            <box size="0.234 0.184 0.08"/>
            </geometry>
        </collision> -->
        <inertial>
            <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
            <mass value="${trunk_mass}"/>
            <inertia
                ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}"
                iyy="${trunk_iyy}" iyz="${trunk_iyz}"
                izz="${trunk_izz}"/>  
        </inertial>
    </link>

    <xacro:if value="${(rolloverProtection == 'true')}">
        <joint name="stick_joint" type="fixed">
            <parent link="trunk"/>
            <child link="stick_link"/>
            <origin rpy="0 0 0" xyz="${0.18} 0 ${stick_length/2.0+0.08}"/>
        </joint>

        <link name="stick_link">
            <visual>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${stick_mass}"/>
                <inertia
                    ixx="${stick_mass / 2.0 * (stick_radius*stick_radius)}" ixy="0.0" ixz="0.0"
                    iyy="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}" iyz="0.0"
                    izz="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}"/>                   
            </inertial>
        </link>
    </xacro:if> 

    <joint name="imu_joint" type="fixed">
        <parent link="trunk"/>
        <child link="imu_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision>
    </link>

    <!-- <xacro:leg name="FR" mirror="-1" mirror_dae="False" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="FL" mirror="1" mirror_dae="True" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="RR" mirror="-1" mirror_dae="False" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="RL" mirror="1" mirror_dae="True" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg> -->

    <!-- <xacro:stairs stairs="15" xpos="0" ypos="2.0" zpos="0" /> -->

  <link
    name="FR_hip">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1.9984" />
      <inertia
        ixx="0.003256"
        ixy="1E-05"
        ixz="6E-06"
        iyy="0.005207"
        iyz="1.8E-05"
        izz="0.004451" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_hip.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_hip.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="FR_hip_joint"
    type="revolute">
    <origin
      xyz="0.29 -0.125 0"
      rpy="0 0 0" />
    <parent
      link="trunk" />
    <child
      link="FR_hip" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="${hip_min*PI/180.0}"
      upper="${hip_max*PI/180.0}"
      effort="${hip_torque_max}"
      velocity="${hip_velocity_max}" />
  </joint>
  <link
    name="FR_thigh">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.375" />
      <inertia
        ixx="0.017933"
        ixy="1.2E-05"
        ixz="0.002123"
        iyy="0.014218"
        iyz="5E-06"
        izz="0.009414" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_thigh.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_thigh.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="FR_thigh_joint"
    type="revolute">
    <origin
      xyz="0 -0.1115 0"
      rpy="0 0 0" />
    <parent
      link="FR_hip" />
    <child
      link="FR_thigh" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${thigh_min*PI/180.0}"
      upper="${thigh_max*PI/180.0}"
      effort="${thigh_torque_max}"
      velocity="${thigh_velocity_max}" />
  </joint>
  <link
    name="FR_calf">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="0.66013" />
      <inertia
        ixx="0.020461"
        ixy="5E-06"
        ixz="0.001151"
        iyy="0.020648"
        iyz="0.000173"
        izz="0.000334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_calf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_calf.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="FR_calf_joint"
    type="revolute">
    <origin
      xyz="0.040673 0 -0.2568"
      rpy="0 0 0" />
    <parent
      link="FR_thigh" />
    <child
      link="FR_calf" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${calf_min*PI/180.0}"
      upper="${calf_max*PI/180.0}"
      effort="${calf_torque_max}"
      velocity="${calf_velocity_max}" />
  </joint>
  <link
    name="FR_wheel">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.4127" />
      <inertia
        ixx="0.006334"
        ixy="0"
        ixz="0"
        iyy="0.011762"
        iyz="0"
        izz="0.006334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FR_wheel.STL" />
      </geometry>
    </collision>
  </link>
  <!-- <joint
    name="FR_wheel_joint"
    type="continuous">
    <origin
      xyz="0.039618 -0.047304 -0.28534"
      rpy="0 0 0" />
    <parent
      link="FR_calf" />
    <child
      link="FR_wheel" />
    <axis
      xyz="0 1 0" />
    <limit
      effort="${wheel_torque_max}"
      velocity="${wheel_velocity_max}" />
  </joint> -->
  <joint
    name="FR_wheel_joint"
    type="fixed">
    <origin
      xyz="0.039618 -0.047304 -0.28534"
      rpy="0 0 0" />
    <parent
      link="FR_calf" />
    <child
      link="FR_wheel" />
  </joint>
  <link
    name="FL_hip">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1.9984" />
      <inertia
        ixx="0.003256"
        ixy="1E-05"
        ixz="6E-06"
        iyy="0.005207"
        iyz="1.8E-05"
        izz="0.004451" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_hip.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_hip.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="FL_hip_joint"
    type="revolute">
    <origin
      xyz="0.29 0.125 0"
      rpy="0 0 0" />
    <parent
      link="trunk" />
    <child
      link="FL_hip" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="${hip_min*PI/180.0}"
      upper="${hip_max*PI/180.0}"
      effort="${hip_torque_max}"
      velocity="${hip_velocity_max}" />
  </joint>
  <link
    name="FL_thigh">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.375" />
      <inertia
        ixx="0.01793"
        ixy="1E-06"
        ixz="0.002121"
        iyy="0.014218"
        iyz="1E-05"
        izz="0.009417" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_thigh.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_thigh.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="FL_thigh_joint"
    type="revolute">
    <origin
      xyz="0 0.1115 0"
      rpy="0 0 0" />
    <parent
      link="FL_hip" />
    <child
      link="FL_thigh" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${thigh_min*PI/180.0}"
      upper="${thigh_max*PI/180.0}"
      effort="${thigh_torque_max}"
      velocity="${thigh_velocity_max}" />
  </joint>
  <link
    name="FL_calf">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="0.66013" />
      <inertia
        ixx="0.020458"
        ixy="1.9E-05"
        ixz="0.001151"
        iyy="0.020648"
        iyz="0.000142"
        izz="0.000331" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_calf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_calf.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="FL_calf_joint"
    type="revolute">
    <origin
      xyz="0.040673 0 -0.2568"
      rpy="0 0 0" />
    <parent
      link="FL_thigh" />
    <child
      link="FL_calf" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${calf_min*PI/180.0}"
      upper="${calf_max*PI/180.0}"
      effort="${calf_torque_max}"
      velocity="${calf_velocity_max}" />
  </joint>
  <link
    name="FL_wheel">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.4127" />
      <inertia
        ixx="0.006334"
        ixy="0"
        ixz="0"
        iyy="0.011762"
        iyz="0"
        izz="0.006334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/FL_wheel.STL" />
      </geometry>
    </collision>
  </link>
  <!-- <joint
    name="FL_wheel_joint"
    type="continuous">
    <origin
      xyz="0.039618 0.0505 -0.28534"
      rpy="0 0 0" />
    <parent
      link="FL_calf" />
    <child
      link="FL_wheel" />
    <axis
      xyz="0 1 0" />
    <limit
      effort="${wheel_torque_max}"
      velocity="${wheel_velocity_max}" />
  </joint> -->
  <joint
    name="FL_wheel_joint"
    type="fixed">
    <origin
      xyz="0.039618 0.0505 -0.28534"
      rpy="0 0 0" />
    <parent
      link="FL_calf" />
    <child
      link="FL_wheel" />
  </joint>
  <link
    name="RR_hip">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1.9984" />
      <inertia
        ixx="0.003256"
        ixy="1E-05"
        ixz="6E-06"
        iyy="0.005207"
        iyz="1.8E-05"
        izz="0.004451" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_hip.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_hip.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="RR_hip_joint"
    type="revolute">
    <origin
      xyz="-0.29 -0.125 0"
      rpy="0 0 0" />
    <parent
      link="trunk" />
    <child
      link="RR_hip" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="${hip_min*PI/180.0}"
      upper="${hip_max*PI/180.0}"
      effort="${hip_torque_max}"
      velocity="${hip_velocity_max}" />
  </joint>
  <link
    name="RR_thigh">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.375" />
      <inertia
        ixx="0.01793"
        ixy="1E-06"
        ixz="0.002121"
        iyy="0.014218"
        iyz="1E-05"
        izz="0.009417" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_thigh.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_thigh.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="RR_thigh_joint"
    type="revolute">
    <origin
      xyz="0 -0.1115 0"
      rpy="0 0 0" />
    <parent
      link="RR_hip" />
    <child
      link="RR_thigh" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${-thigh_max*PI/180.0}"
      upper="${-thigh_min*PI/180.0}"
      effort="${thigh_torque_max}"
      velocity="${thigh_velocity_max}" />
  </joint>
  <link
    name="RR_calf">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="0.66013" />
      <inertia
        ixx="0.020458"
        ixy="1.9E-05"
        ixz="0.001151"
        iyy="0.020648"
        iyz="0.000142"
        izz="0.000331" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_calf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_calf.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="RR_calf_joint"
    type="revolute">
    <origin
      xyz="-0.040673 0 -0.2568"
      rpy="0 0 0" />
    <parent
      link="RR_thigh" />
    <child
      link="RR_calf" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${-calf_max*PI/180.0}"
      upper="${-calf_min*PI/180.0}"
      effort="${calf_torque_max}"
      velocity="${calf_velocity_max}" />
  </joint>
  <link
    name="RR_wheel">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.4127" />
      <inertia
        ixx="0.006334"
        ixy="0"
        ixz="0"
        iyy="0.011762"
        iyz="0"
        izz="0.006334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RR_wheel.STL" />
      </geometry>
    </collision>
  </link>
  <!-- <joint
    name="RR_wheel_joint"
    type="continuous">
    <origin
      xyz="-0.039618 -0.0505 -0.28534"
      rpy="0 0 0" />
    <parent
      link="RR_calf" />
    <child
      link="RR_wheel" />
    <axis
      xyz="0 1 0" />
    <limit
      effort="${wheel_torque_max}"
      velocity="${wheel_velocity_max}" />
  </joint> -->
  <joint
    name="RR_wheel_joint"
    type="fixed">
    <origin
      xyz="-0.039618 -0.0505 -0.28534"
      rpy="0 0 0" />
    <parent
      link="RR_calf" />
    <child
      link="RR_wheel" />
  </joint>
  <link
    name="RL_hip">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1.9984" />
      <inertia
        ixx="0.003256"
        ixy="1E-05"
        ixz="6E-06"
        iyy="0.005207"
        iyz="1.8E-05"
        izz="0.004451" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_hip.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_hip.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="RL_hip_joint"
    type="revolute">
    <origin
      xyz="-0.29 0.125 0"
      rpy="0 0 0" />
    <parent
      link="trunk" />
    <child
      link="RL_hip" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="${hip_min*PI/180.0}"
      upper="${hip_max*PI/180.0}"
      effort="${hip_torque_max}"
      velocity="${hip_velocity_max}" />
  </joint>
  <link
    name="RL_thigh">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.375" />
      <inertia
        ixx="0.017933"
        ixy="1.2E-05"
        ixz="0.002123"
        iyy="0.014218"
        iyz="5E-06"
        izz="0.009414" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_thigh.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_thigh.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="RL_thigh_joint"
    type="revolute">
    <origin
      xyz="0 0.1115 0"
      rpy="0 0 0" />
    <parent
      link="RL_hip" />
    <child
      link="RL_thigh" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${-thigh_max*PI/180.0}"
      upper="${-thigh_min*PI/180.0}"
      effort="${thigh_torque_max}"
      velocity="${thigh_velocity_max}" />
  </joint>
  <link
    name="RL_calf">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="0.66013" />
      <inertia
        ixx="0.020461"
        ixy="5E-06"
        ixz="0.001151"
        iyy="0.020648"
        iyz="0.000173"
        izz="0.000334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_calf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_calf.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="RL_calf_joint"
    type="revolute">
    <origin
      xyz="-0.040673 0 -0.2568"
      rpy="0 0 0" />
    <parent
      link="RL_thigh" />
    <child
      link="RL_calf" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="${-calf_max*PI/180.0}"
      upper="${-calf_min*PI/180.0}"
      effort="${calf_torque_max}"
      velocity="${calf_velocity_max}" />
  </joint>
  <link
    name="RL_wheel">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2.4127" />
      <inertia
        ixx="0.006334"
        ixy="0"
        ixz="0"
        iyy="0.011762"
        iyz="0"
        izz="0.006334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79608 0.82353 0.93725 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://njust_v2_fixed_description/meshes/RL_wheel.STL" />
      </geometry>
    </collision>
  </link>
  <!-- <joint
    name="RL_wheel_joint"
    type="continuous">
    <origin
      xyz="-0.039618 0.047304 -0.28534"
      rpy="0 0 0" />
    <parent
      link="RL_calf" />
    <child
      link="RL_wheel" />
    <axis
      xyz="0 -1 0" />
    <limit
      effort="${wheel_torque_max}"
      velocity="${wheel_velocity_max}" />
  </joint> -->
  <joint
    name="RL_wheel_joint"
    type="fixed">
    <origin
      xyz="-0.039618 0.047304 -0.28534"
      rpy="0 0 0" />
    <parent
      link="RL_calf" />
    <child
      link="RL_wheel" />
  </joint>

  <xacro:leg_transmission name="FR"/>
  <xacro:leg_transmission name="FL"/>
  <xacro:leg_transmission name="RR"/>
  <xacro:leg_transmission name="RL"/>

</robot>
